DROP DATABASE ShopDB
GO

CREATE DATABASE ShopDB
GO

USE ShopDB
GO

/*
ALTER DATABASE ShopDB SET ANSI_NULLS ON

ALTER DATABASE ShopDB SET QUOTED_IDENTIFIER ON

ALTER DATABASE ShopDB SET ANSI_PADDING ON

ALTER DATABASE ShopDB SET ANSI_WARNINGS ON

ALTER DATABASE ShopDB SET CONCAT_NULL_YIELDS_NULL ON

ALTER DATABASE ShopDB SET NUMERIC_ROUNDABORT OFF

ALTER DATABASE ShopDB SET ARITHABORT ON
*/
 

ALTER DATABASE ShopDB
  SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE
GO

DROP TABLE Product
GO

CREATE TABLE Product
( Id INT IDENTITY PRIMARY KEY 
, Name VARCHAR(50) NOT NULL
, Price MONEY NOT NULL CHECK(Price > 0)
, Date DATETIME NOT NULL
)
GO

INSERT INTO Product(Name, Price, Date)
  VALUES('Телефон', 2700, '25-05-2023 19:40')
GO
INSERT INTO Product(Name, Price, Date)
  VALUES('Ноутбук', 2700, '09-06-2023 17:20')
GO
INSERT INTO Product(Name, Price, Date)
  VALUES('Калькулятор', 2700, '25-06-2023 14:17')
GO

--ALTER DATABASE ShopDB SET DISABLE_BROKER;

--ALTER DATABASE ShopDB SET ENABLE_BROKER
--GO

--CREATE QUEUE SBInitiatorQueue
--GO

--CREATE SERVICE SBInitiatorService
--ON QUEUE SBInitiatorQueue
--GO
